modLoader = "javafml"
loaderVersion = "[47,)"
license = "Apache 2.0"

[[mods]]
modId = "authplugin"
version = "${version}"
displayName = "AuthPlugin"
authors = ""
description = '''

'''

[[dependencies.authplugin]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.authplugin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.authplugin]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "authplugin.mixins.json"
